### ISSUE TITLE
the preview don't work

### ISSUE THREAD

**Issue by enhancer** [attilabuti/vscode-mjml#17]
Hi,
The preview don't work , with mjml file i have no message to this code :
<mjml>
    <mj-body>
      <mj-container>
        <mj-section>
          <mj-column>
            <mj-text>Hello World!</mj-text>
          </mj-column>
        </mj-section>
      </mj-container>
    </mj-body>
  </mjml>

with the html file i have the message "Active editor doesn't show a MJML document."

**Comment by attilabuti** [comment]
Hello @enhancer

The preview doesn't work, because the "Hello World!" is not a valid MJML document.

MJML CLI: 
`Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.`

Working example:
```mjml
<mjml>
    <mj-body>
        <mj-container>
            <mj-section>
                <mj-column>
                    <mj-text>Hello, World!</mj-text>
                </mj-column>
            </mj-section>
        </mj-container>
    </mj-body>
</mjml>
```

[MJML Documentation](https://mjml.io/documentation/#mjml-guides)
