### ISSUE TITLE
Question: MJML couldn't build the propper version of PhantomJS

### ISSUE THREAD

**Issue by frankis** [attilabuti/vscode-mjml#30]
Just installed a new machine (macOS - 1.13.4) with vscode (1.23.1) with the mjml extension (1.3.0) which basically results in the following:

> MJML couldn't build the propper version of PhantomJS. Restart VSCode in order to try it again.

Followed by:
> MJML needs to be rebuilt for your current platform. Please wait for the installation to finish...

As its mentioned that there are no dependencies I wonder whats missing here?

**Comment by gil04** [comment]
Same problem here...

**Comment by attilabuti** [comment]
@frankis Could you please try the following?

```
npm install phantomjs-prebuilt
npm --strict-ssl false rebuild phantomjs-prebuilt
```

Let me know if this works for you. Thanks!

**Comment by gil04** [comment]
npm was not installed. After installing npm the error message is gone and the screenshots are working as expected. Thx!

**Comment by codyhazelwood** [comment]
I'm seeing the same issue here.  I don't have a global node install though (using `nvm`).  Normally installing the node modules manually at the VS Code workspace root works, but it doesn't here.

**Comment by attilabuti** [comment]
Thank you for reporting – I will fix it in the next update.

**Comment by attilabuti** [comment]
The issue is fixed on 1.4.0.

**Comment by RobertDessin** [comment]
no. its not. 
v1.6.0: MJML couldn't build the proper version of PhantomJS. Restart VSCode in order to try it again.

**Comment by bertobox** [comment]
I’m experiencing the same issue.

My current setup is macOS Mojave 10.14.4, VSCode 1.35.1, mjml extension 1.6.0

**Comment by vcorvid** [comment]
I am also experiencing this issue on Mac Mojave

**Comment by theCalibrius** [comment]
I was encountering this issue and it seemed related to:

-MacOS could not identify the developer of phantomJS and was not allowing it to be installed.  The computer I'm on does not allow me to override this behavior of MacOS.

-PhantomJS is not allowed to be downloaded via npm on my computer due to the package having (supposed) known vulnerabilities, as identified by third-party security service proxy that we use.

I tried to use phantomjs-prebuilt to get around this restriction, and it worked.

I ran ```npm install phantomjs-prebuilt -g```
It had some hiccups (trying to use version of phantomjs it discovered on my system but that failed)
but eventually it installed.

I restarted vscode and then tried running mjml commands in vscode and it gave me the "building mjml for your system" popup, but this time it worked just fine.
